part = ' -'*4+' '
spaces = len(part)
def do_four(function, a):
    function(a)
    function(a)
    function(a)
    function(a)
def draw_table_2x2():
    horizontal_row = (('+'+part)*2+'+')
    vertical_row = (('|'+' '*spaces)*2+'|')
    print(horizontal_row)
    do_four(print, vertical_row)
    print(horizontal_row)
    do_four(print, vertical_row)
    print(horizontal_row)
draw_table_2x2()
def draw_table_4x4():
    horizontal_row1 = (('+'+part)*4+'+')
    vertical_row1 = (('|'+' '*spaces)*4+'|')
    print(horizontal_row1)
    do_four(print, vertical_row1)
    print(horizontal_row1)
    do_four(print, vertical_row1)
    print(horizontal_row1)
    do_four(print, vertical_row1)
    print(horizontal_row1)
    do_four(print, vertical_row1)
    print(horizontal_row1)
draw_table_4x4()
